### ISSUE TITLE
mouse-speed not selectable

### ISSUE THREAD

**Issue by ghost** [gps79/Amiga-Laser-Mouse-ADNS-9800#1]
hi @gps79 ,

i built a new amiga-laser-mouse with your fine piece of software and a pcb from pcbway-shared projects.
i use a PIC 18F26K22 and everything went fine.

big thanks for your awesome work.

but i've got an urgent feature-request (not an issue so far)

the mouse pointer went really fast over the whole screen. on the PCB is a jumper called "CFG". as written by the PCB engeneer, it is possible so set the DPI with the LMB while using this jumper.

if i use the jumper with your firmware, there will only start a "demo-mode". i lookked into the code, but did not found a solution for changing DPI/mouse-speed.

could you provide a "fix" or a possibility to set the DPI?

thanks and regards Maddis.

**Comment by gps79** [comment]
Hello @maddis4free ,
Great to hear that you find the software useful.
Current software already contains DPI setting. It's called "calibration" here.

To enter the calibration mode:
- press both buttons on the mouse
- connect the mouse to the computer (it is important that the buttons are pressed when starting the mouse software)
- release both buttons on the mouse
Calibration is done in the range of 50-8200cpi (points per inch) with a starting calibration value of 3400cpi (the standard Amiga mouse is about 200cpi) and a step of 50cpi.
- press the left mouse button to increase the speed / sensitivity of the mouse by 50cpi - the mouse cursor will move slightly upwards confirming the change
- press the right mouse button to decrease the speed / sensitivity of the mouse by 50cpi - the mouse cursor will move slightly downwards confirming the change
When attempting to exceed the calibration limits (50 or 8200cpi), the mouse cursor will shake on the horizontal axis.
The new calibration value is saved in the EEPROM immediately and will be used for the next calibration.
In the calibration mode, mouse buttons press signals are not transferred to the computer.
To exit the calibration mode press both buttons of the mouse. Exiting the calibration mode will be confirmed by "drawing" a "V" shape on the screen.

You can read more in the forum where I described the changes in the software during development (you can use the translation from Polish): https://www.elektroda.pl/rtvforum/topic3821709.html

**Comment by ghost** [comment]
hi @gps79 ,

you made my day!!! 🥇 

i tried the calibration-mode, and everything works like a charm. now i'm happy, thank you very much.


regards, Maddis 👍
