### ISSUE TITLE
RMB problem on Amiga 600&1200

### ISSUE THREAD

**Issue by ghost** [gps79/Amiga-Laser-Mouse-ADNS-9800#2]
hi @gps79 ,

on my amiga500 (rev 3 & 8) the mouse is working fine. 

but on my amiga1200 & amiga600 i've got a problem with the right mouse button, the RMB won't be gecognized while pressing.
the voltage an the pin drops while pressig the button, but nothing happen. this is wierd, because the early-boot-menu is working. o_O

edit: the voltage while pressing the RMB only drops to 0.4V, this seems to be to high for the amiga for a trigger. o_O

a direct wiring between the button & pin will work, but thats no solution.

do you have any ideas?

regards, Maddis

ps: i also have a feature request: could you switch the output-pins 2&3? so we can use the original wiring of the mouse-cable-plug (otherwise we have to switch the pins in the plug. ;) )

ps2: i use a PIC18F24K22, just FYI

thanx!

**Comment by gps79** [comment]
In the firmware there is no difference in LMB and RMB handling. I believe removing the R1 resistor may help.
[https://obrazki.elektroda.pl/9915052300_1629740551_org.jpg](https://obrazki.elektroda.pl/9915052300_1629740551_org.jpg)

**Comment by ghost** [comment]
hi @gps79 ,

i'll try and test. (i only removed R4 but got no result. on the shemata R4 is named as the pullup for the RMB o_O)
i let you know, if the remove of R1 take effect. 


thanx, Maddis

**Comment by ghost** [comment]
hi @gps79 ,

removing the R1 pullup did the trick, now also my A600 & A1200 are fully working with this laser-mouse!

thank you very much. :)
